qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/16438.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/16488.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/16840.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/16929.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/16972.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17049.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17054.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17068.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17081.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17087.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17109.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17115.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17130.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17701.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/17812.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/18294.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/18349.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/18596.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/18655.gtf
qsub ~/LabNotes/SubmissionScripts/IGVtools.sh /c8000xd3/rnaseq-heath/Cufflinks/Cuffcompare/18687.gtf