---
title: "Data QC"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyr)
library(ggplot2)
library(dplyr)
library(cowplot)
library(gridExtra)
```
## Insert Sizes
- 20.7% of reads have an insert size of zero
- 10.9% have an insert size > 5000 bp
- BIG jump right at 1000 bp, stays high until 1750, then gradually declines

```{r}

insert_sizes <- read.delim("/Users/heo3/BTSync/FetalRNAseq/BamQC/15533_300/insert_sizes.txt", header=TRUE, stringsAsFactors=FALSE)
colnames(insert_sizes)<-c('size', 'percent')
sum(insert_sizes[insert_sizes$size > 5000, 2])
insert_sizes[1,2]
ggplot(insert_sizes[insert_sizes$size > 0 & insert_sizes$size < 5001,], aes(x=size, y=percent)) +geom_line()

```

## Picard RNAseq Stats


```{r }
RnaSeqMetrics <- read.delim("~/BTSync/FetalRNAseq/BamQC/15533_300/RnaSeqMetrics.txt", header=TRUE, comment.char="#", stringsAsFactors = FALSE)

cov <- data.frame(normalized_position=as.numeric(RnaSeqMetrics[-(1:2),]$PF_BASES), normalized_coverage=as.numeric(RnaSeqMetrics[-(1:2),]$PF_ALIGNED_BASES))
RnaSeqMetrics <- RnaSeqMetrics[(1),]
```


